#include "src/game/envfx_snow.h"

const GeoLayout mr_i_eyeball_closed2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_ALPHA, mr_i_eyeball_000_switch_closed_mesh_layer_4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mr_i_eyeball_mostlyopen2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_ALPHA, mr_i_eyeball_000_switch_mostlyopen_mesh_layer_4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mr_i_eyeball_mostlyclosed2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_ALPHA, mr_i_eyeball_000_switch_mostlyclosed_mesh_layer_4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mr_i_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_NODE_START(),
		GEO_OPEN_NODE(),
			GEO_SWITCH_CASE(20, geo_switch_anim_state),
			GEO_OPEN_NODE(),
				GEO_NODE_START(),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_ALPHA, mr_i_eyeball_000_displaylist_mesh_layer_4),
				GEO_CLOSE_NODE(),
				GEO_BRANCH(1, mr_i_eyeball_closed2),
				GEO_BRANCH(1, mr_i_eyeball_mostlyopen2),
				GEO_BRANCH(1, mr_i_eyeball_mostlyclosed2),
				GEO_BRANCH(1, mr_i_eyeball_closed2),
				GEO_BRANCH(1, mr_i_eyeball_mostlyclosed2),
				GEO_BRANCH(1, mr_i_eyeball_mostlyopen2),
				GEO_BRANCH(1, mr_i_eyeball_closed2),
				GEO_BRANCH(1, mr_i_eyeball_closed2),
				GEO_BRANCH(1, mr_i_eyeball_closed2),
				GEO_BRANCH(1, mr_i_eyeball_mostlyopen2),
				GEO_BRANCH(1, mr_i_eyeball_mostlyclosed2),
				GEO_BRANCH(1, mr_i_eyeball_closed2),
				GEO_BRANCH(1, mr_i_eyeball_mostlyclosed2),
				GEO_BRANCH(1, mr_i_eyeball_mostlyopen2),
				GEO_BRANCH(1, mr_i_eyeball_closed2),
				GEO_BRANCH(1, mr_i_eyeball_closed2),
				GEO_BRANCH(1, mr_i_eyeball_closed2),
				GEO_BRANCH(1, mr_i_eyeball_closed2),
				GEO_BRANCH(1, mr_i_eyeball_closed2),
				GEO_BRANCH(1, mr_i_eyeball_closed2),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_ALPHA, mr_i_eyeball_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
