extern const GeoLayout mr_i_eyeball_closed2[];
extern const GeoLayout mr_i_eyeball_mostlyopen2[];
extern const GeoLayout mr_i_eyeball_mostlyclosed2[];
extern const GeoLayout mr_i_geo[];
extern Lights1 mr_i_eyeball_eye_ball_lights;
extern Lights1 mr_i_eyeball_eye_open_lights;
extern Lights1 mr_i_eyeball_eye_closed_lights;
extern Lights1 mr_i_eyeball_eye_mostlyopen_lights;
extern Lights1 mr_i_eyeball_eye_mostlyclosed_lights;
extern u8 mr_i_eyeball_mr_i_iris_open_rgba16_rgba32[];
extern u8 mr_i_eyeball_mr_i_iris_closed_rgba16_rgba32[];
extern Vtx mr_i_eyeball_000_displaylist_mesh_layer_4_vtx_0[187];
extern Gfx mr_i_eyeball_000_displaylist_mesh_layer_4_tri_0[];
extern Vtx mr_i_eyeball_000_displaylist_mesh_layer_4_vtx_1[57];
extern Gfx mr_i_eyeball_000_displaylist_mesh_layer_4_tri_1[];
extern Vtx mr_i_eyeball_000_switch_closed_mesh_layer_4_vtx_0[43];
extern Gfx mr_i_eyeball_000_switch_closed_mesh_layer_4_tri_0[];
extern Vtx mr_i_eyeball_000_switch_closed_mesh_layer_4_vtx_1[187];
extern Gfx mr_i_eyeball_000_switch_closed_mesh_layer_4_tri_1[];
extern Vtx mr_i_eyeball_000_switch_mostlyopen_mesh_layer_4_vtx_0[99];
extern Gfx mr_i_eyeball_000_switch_mostlyopen_mesh_layer_4_tri_0[];
extern Vtx mr_i_eyeball_000_switch_mostlyopen_mesh_layer_4_vtx_1[187];
extern Gfx mr_i_eyeball_000_switch_mostlyopen_mesh_layer_4_tri_1[];
extern Vtx mr_i_eyeball_000_switch_mostlyclosed_mesh_layer_4_vtx_0[108];
extern Gfx mr_i_eyeball_000_switch_mostlyclosed_mesh_layer_4_tri_0[];
extern Vtx mr_i_eyeball_000_switch_mostlyclosed_mesh_layer_4_vtx_1[187];
extern Gfx mr_i_eyeball_000_switch_mostlyclosed_mesh_layer_4_tri_1[];
extern Gfx mat_mr_i_eyeball_eye_ball[];
extern Gfx mat_mr_i_eyeball_eye_open[];
extern Gfx mat_mr_i_eyeball_eye_closed[];
extern Gfx mat_mr_i_eyeball_eye_mostlyopen[];
extern Gfx mat_mr_i_eyeball_eye_mostlyclosed[];
extern Gfx mr_i_eyeball_000_displaylist_mesh_layer_4[];
extern Gfx mr_i_eyeball_000_switch_closed_mesh_layer_4[];
extern Gfx mr_i_eyeball_000_switch_mostlyopen_mesh_layer_4[];
extern Gfx mr_i_eyeball_000_switch_mostlyclosed_mesh_layer_4[];
extern Gfx mr_i_eyeball_material_revert_render_settings[];
