extern const GeoLayout spiky_tree_geo[];
extern Lights1 tree_trunk_lights;
extern Lights1 tree_leaves_lights;
extern u8 tree_trunk_rgba16[];
extern u8 tree_pine_middle_rgba16[];
extern Vtx tree_spiky_displaylist_mesh_layer_1_vtx_0[35];
extern Gfx tree_spiky_displaylist_mesh_layer_1_tri_0[];
extern Vtx tree_spiky_displaylist_mesh_layer_1_vtx_1[72];
extern Gfx tree_spiky_displaylist_mesh_layer_1_tri_1[];
extern Gfx mat_tree_trunk[];
extern Gfx mat_tree_leaves[];
extern Gfx tree_spiky_displaylist_mesh_layer_1[];
extern Gfx tree_material_revert_render_settings[];

extern const GeoLayout snow_tree_geo[];
extern Lights1 tree_trunk_lights;
extern Lights1 tree_snowy_leaves_lights;
extern u8 tree_snow_trunk_rgba16[];
extern u8 tree_snow_leaves_rgba16[];
extern Vtx tree_snow_displaylist_mesh_layer_1_vtx_0[35];
extern Gfx tree_snow_displaylist_mesh_layer_1_tri_0[];
extern Vtx tree_snow_displaylist_mesh_layer_1_vtx_1[81];
extern Gfx tree_snow_displaylist_mesh_layer_1_tri_1[];
extern Gfx mat_tree_trunk[];
extern Gfx mat_tree_snowy_leaves[];
extern Gfx tree_snow_displaylist_mesh_layer_1[];
extern Gfx tree_material_revert_render_settings[];

extern const GeoLayout palm_tree_geo[];
extern Lights1 tree_trunk_lights;
extern Lights1 tree_leaves_lights;
extern u8 tree_trunk_rgba16[];
extern u8 tree_bubbly_leaves_rgba16[];
extern Vtx tree_palm_displaylist_mesh_layer_1_vtx_0[41];
extern Gfx tree_palm_displaylist_mesh_layer_1_tri_0[];
extern Vtx tree_palm_displaylist_mesh_layer_1_vtx_1[180];
extern Gfx tree_palm_displaylist_mesh_layer_1_tri_1[];
extern Gfx mat_tree_trunk[];
extern Gfx mat_tree_leaves[];
extern Gfx tree_palm_displaylist_mesh_layer_1[];
extern Gfx tree_material_revert_render_settings[];

extern const GeoLayout bubbly_tree_geo[];
extern Lights1 tree_leaves_lights;
extern Lights1 tree_trunk_lights;
extern u8 tree_bubbly_leaves_rgba16[];
extern u8 tree_trunk_rgba16[];
extern Vtx tree_bubbly_displaylist_mesh_layer_1_vtx_0[163];
extern Gfx tree_bubbly_displaylist_mesh_layer_1_tri_0[];
extern Vtx tree_bubbly_displaylist_mesh_layer_1_vtx_1[35];
extern Gfx tree_bubbly_displaylist_mesh_layer_1_tri_1[];
extern Gfx mat_tree_leaves[];
extern Gfx mat_tree_trunk[];
extern Gfx tree_bubbly_displaylist_mesh_layer_1[];
extern Gfx tree_material_revert_render_settings[];
