extern const GeoLayout boo_key_geo[];
extern Lights1 boo_key_coin_luigi_right_v4_lights;
extern Lights1 boo_key_coin_luigi_left_v4_lights;
extern u8 boo_key_coin_luigi_right_rgba32[];
extern u8 boo_key_coin_luigi_left_rgba32[];
extern Vtx boo_key_skinned_001_mesh_layer_1_vtx_0[10];
extern Gfx boo_key_skinned_001_mesh_layer_1_tri_0[];
extern Vtx boo_key_skinned_001_mesh_layer_1_vtx_1[40];
extern Gfx boo_key_skinned_001_mesh_layer_1_tri_1[];
extern Gfx mat_boo_key_coin_luigi_right_v4[];
extern Gfx mat_boo_key_coin_luigi_left_v4[];
extern Gfx boo_key_skinned_001_mesh_layer_1[];
extern Gfx boo_key_material_revert_render_settings[];
