#include "src/game/envfx_snow.h"

const GeoLayout wario_coin_pumpkin_geo[] = {
    GEO_SHADOW(SHADOW_CIRCLE_4_VERTS, 0xB4, 50),
    GEO_OPEN_NODE(),
        GEO_ASM(0, geo_rotate_coin),
        GEO_ROTATION_NODE(0x00, 0, 0, 0),
        GEO_OPEN_NODE(),
            GEO_SCALE(0, 0x4E20),
            GEO_OPEN_NODE(),
                GEO_TRANSLATE_ROTATE(1, 0, 170, 0, 0, 0, 180),
                GEO_OPEN_NODE(),
                    GEO_DISPLAY_LIST(LAYER_OPAQUE, wario_coin_pumpkin),
                    GEO_DISPLAY_LIST(1, wario_coin_material_revert_render_settings),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};

const GeoLayout wario_coin_house_geo[] = {
	GEO_SHADOW(SHADOW_CIRCLE_4_VERTS, 0xB4, 50),
    GEO_OPEN_NODE(),
        GEO_ASM(0, geo_rotate_coin),
        GEO_ROTATION_NODE(0x00, 0, 0, 0),
        GEO_OPEN_NODE(),
            GEO_SCALE(0, 0x4E20),
            GEO_OPEN_NODE(),
                GEO_TRANSLATE_ROTATE(1, 0, 170, 0, 0, 0, 180),
                GEO_OPEN_NODE(),
                    GEO_DISPLAY_LIST(LAYER_OPAQUE, wario_coin_pumpkin),
                    GEO_DISPLAY_LIST(1, wario_coin_material_revert_render_settings),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};

const GeoLayout wario_coin_tree_geo[] = {
	GEO_SHADOW(SHADOW_CIRCLE_4_VERTS, 0xB4, 50),
    GEO_OPEN_NODE(),
        GEO_ASM(0, geo_rotate_coin),
        GEO_ROTATION_NODE(0x00, 0, 0, 0),
        GEO_OPEN_NODE(),
            GEO_SCALE(0, 0x4E20),
            GEO_OPEN_NODE(),
                GEO_TRANSLATE_ROTATE(1, 0, 170, 0, 0, 0, 180),
                GEO_OPEN_NODE(),
                    GEO_DISPLAY_LIST(LAYER_OPAQUE, wario_coin_pumpkin),
                    GEO_DISPLAY_LIST(1, wario_coin_material_revert_render_settings),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};

const GeoLayout wario_coin_koopa_geo[] = {
	GEO_SHADOW(SHADOW_CIRCLE_4_VERTS, 0xB4, 50),
    GEO_OPEN_NODE(),
        GEO_ASM(0, geo_rotate_coin),
        GEO_ROTATION_NODE(0x00, 0, 0, 0),
        GEO_OPEN_NODE(),
            GEO_SCALE(0, 0x4E20),
            GEO_OPEN_NODE(),
                GEO_TRANSLATE_ROTATE(1, 0, 170, 0, 0, 0, 180),
                GEO_OPEN_NODE(),
                    GEO_DISPLAY_LIST(LAYER_OPAQUE, wario_coin_pumpkin),
                    GEO_DISPLAY_LIST(1, wario_coin_material_revert_render_settings),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};

const GeoLayout wario_coin_lunar_geo[] = {
	GEO_SHADOW(SHADOW_CIRCLE_4_VERTS, 0xB4, 50),
    GEO_OPEN_NODE(),
        GEO_ASM(0, geo_rotate_coin),
        GEO_ROTATION_NODE(0x00, 0, 0, 0),
        GEO_OPEN_NODE(),
            GEO_SCALE(0, 0x4E20),
            GEO_OPEN_NODE(),
                GEO_TRANSLATE_ROTATE(1, 0, 170, 0, 0, 0, 180),
                GEO_OPEN_NODE(),
                    GEO_DISPLAY_LIST(LAYER_OPAQUE, wario_coin_pumpkin),
                    GEO_DISPLAY_LIST(1, wario_coin_material_revert_render_settings),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};

const GeoLayout wario_coin_mario_geo[] = {
	GEO_SHADOW(SHADOW_CIRCLE_4_VERTS, 0xB4, 50),
    GEO_OPEN_NODE(),
        GEO_ASM(0, geo_rotate_coin),
        GEO_ROTATION_NODE(0x00, 0, 0, 0),
        GEO_OPEN_NODE(),
            GEO_SCALE(0, 0x4E20),
            GEO_OPEN_NODE(),
                GEO_TRANSLATE_ROTATE(1, 0, 170, 0, 0, 0, 180),
                GEO_OPEN_NODE(),
                    GEO_DISPLAY_LIST(LAYER_OPAQUE, wario_coin_pumpkin),
                    GEO_DISPLAY_LIST(1, wario_coin_material_revert_render_settings),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};
