#include "src/game/envfx_snow.h"

const GeoLayout warp_pipe_boo_geo[] = { //blue pipe
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_CULLING_RADIUS(1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(1, warp_pipe_boo_000_displaylist_mesh),
			GEO_DISPLAY_LIST(1, warp_pipe_boo_001_displaylist_mesh),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(0, warp_pipe_boo_material_revert_render_settings),
		GEO_DISPLAY_LIST(1, warp_pipe_boo_material_revert_render_settings),
		GEO_DISPLAY_LIST(2, warp_pipe_boo_material_revert_render_settings),
		GEO_DISPLAY_LIST(3, warp_pipe_boo_material_revert_render_settings),
		GEO_DISPLAY_LIST(4, warp_pipe_boo_material_revert_render_settings),
		GEO_DISPLAY_LIST(5, warp_pipe_boo_material_revert_render_settings),
		GEO_DISPLAY_LIST(6, warp_pipe_boo_material_revert_render_settings),
		GEO_DISPLAY_LIST(7, warp_pipe_boo_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};

const GeoLayout warp_pipe_boo_green_locked_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_CULLING_RADIUS(745),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(1, warp_pipe_boo_green_locked_000_displaylist_mesh),
			GEO_DISPLAY_LIST(1, warp_pipe_boo_green_locked_001_displaylist_mesh),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(0, warp_pipe_boo_green_locked_material_revert_render_settings),
		GEO_DISPLAY_LIST(1, warp_pipe_boo_green_locked_material_revert_render_settings),
		GEO_DISPLAY_LIST(2, warp_pipe_boo_green_locked_material_revert_render_settings),
		GEO_DISPLAY_LIST(3, warp_pipe_boo_green_locked_material_revert_render_settings),
		GEO_DISPLAY_LIST(4, warp_pipe_boo_green_locked_material_revert_render_settings),
		GEO_DISPLAY_LIST(5, warp_pipe_boo_green_locked_material_revert_render_settings),
		GEO_DISPLAY_LIST(6, warp_pipe_boo_green_locked_material_revert_render_settings),
		GEO_DISPLAY_LIST(7, warp_pipe_boo_green_locked_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};

const GeoLayout warp_pipe_boo_green_unlocked_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_CULLING_RADIUS(745),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(1, warp_pipe_boo_green_unlocked_000_displaylist_mesh),
			GEO_DISPLAY_LIST(1, warp_pipe_boo_green_unlocked_001_displaylist_mesh),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(0, warp_pipe_boo_green_unlocked_material_revert_render_settings),
		GEO_DISPLAY_LIST(1, warp_pipe_boo_green_unlocked_material_revert_render_settings),
		GEO_DISPLAY_LIST(2, warp_pipe_boo_green_unlocked_material_revert_render_settings),
		GEO_DISPLAY_LIST(3, warp_pipe_boo_green_unlocked_material_revert_render_settings),
		GEO_DISPLAY_LIST(4, warp_pipe_boo_green_unlocked_material_revert_render_settings),
		GEO_DISPLAY_LIST(5, warp_pipe_boo_green_unlocked_material_revert_render_settings),
		GEO_DISPLAY_LIST(6, warp_pipe_boo_green_unlocked_material_revert_render_settings),
		GEO_DISPLAY_LIST(7, warp_pipe_boo_green_unlocked_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};

const GeoLayout warp_pipe_boo_red_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_CULLING_RADIUS(745),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(1, warp_pipe_boo_red_000_displaylist_mesh),
			GEO_DISPLAY_LIST(1, warp_pipe_boo_red_001_displaylist_mesh),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(0, warp_pipe_boo_red_material_revert_render_settings),
		GEO_DISPLAY_LIST(1, warp_pipe_boo_red_material_revert_render_settings),
		GEO_DISPLAY_LIST(2, warp_pipe_boo_red_material_revert_render_settings),
		GEO_DISPLAY_LIST(3, warp_pipe_boo_red_material_revert_render_settings),
		GEO_DISPLAY_LIST(4, warp_pipe_boo_red_material_revert_render_settings),
		GEO_DISPLAY_LIST(5, warp_pipe_boo_red_material_revert_render_settings),
		GEO_DISPLAY_LIST(6, warp_pipe_boo_red_material_revert_render_settings),
		GEO_DISPLAY_LIST(7, warp_pipe_boo_red_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};

const GeoLayout warp_pipe_boo_yellow_locked_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_CULLING_RADIUS(745),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(1, warp_pipe_boo_yellow_locked_000_displaylist_mesh),
			GEO_DISPLAY_LIST(1, warp_pipe_boo_yellow_locked_001_displaylist_mesh),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(0, warp_pipe_boo_yellow_locked_material_revert_render_settings),
		GEO_DISPLAY_LIST(1, warp_pipe_boo_yellow_locked_material_revert_render_settings),
		GEO_DISPLAY_LIST(2, warp_pipe_boo_yellow_locked_material_revert_render_settings),
		GEO_DISPLAY_LIST(3, warp_pipe_boo_yellow_locked_material_revert_render_settings),
		GEO_DISPLAY_LIST(4, warp_pipe_boo_yellow_locked_material_revert_render_settings),
		GEO_DISPLAY_LIST(5, warp_pipe_boo_yellow_locked_material_revert_render_settings),
		GEO_DISPLAY_LIST(6, warp_pipe_boo_yellow_locked_material_revert_render_settings),
		GEO_DISPLAY_LIST(7, warp_pipe_boo_yellow_locked_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};

const GeoLayout warp_pipe_boo_yellow_unlocked_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_CULLING_RADIUS(745),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(1, warp_pipe_boo_yellow_unlocked_000_displaylist_mesh),
			GEO_DISPLAY_LIST(1, warp_pipe_boo_yellow_unlocked_001_displaylist_mesh),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(0, warp_pipe_boo_yellow_unlocked_material_revert_render_settings),
		GEO_DISPLAY_LIST(1, warp_pipe_boo_yellow_unlocked_material_revert_render_settings),
		GEO_DISPLAY_LIST(2, warp_pipe_boo_yellow_unlocked_material_revert_render_settings),
		GEO_DISPLAY_LIST(3, warp_pipe_boo_yellow_unlocked_material_revert_render_settings),
		GEO_DISPLAY_LIST(4, warp_pipe_boo_yellow_unlocked_material_revert_render_settings),
		GEO_DISPLAY_LIST(5, warp_pipe_boo_yellow_unlocked_material_revert_render_settings),
		GEO_DISPLAY_LIST(6, warp_pipe_boo_yellow_unlocked_material_revert_render_settings),
		GEO_DISPLAY_LIST(7, warp_pipe_boo_yellow_unlocked_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
