extern const GeoLayout warp_pipe_boo_geo[];
extern Vtx warp_pipe_boo_000_displaylist_mesh_vtx_0[64];
extern Gfx warp_pipe_boo_000_displaylist_mesh_tri_0[];
extern Vtx warp_pipe_boo_001_displaylist_mesh_vtx_0[4];
extern Gfx warp_pipe_boo_001_displaylist_mesh_tri_0[];
extern Vtx warp_pipe_boo_001_displaylist_mesh_vtx_1[16];
extern Gfx warp_pipe_boo_001_displaylist_mesh_tri_1[];

extern Gfx warp_pipe_boo_000_displaylist_mesh[];
extern Gfx warp_pipe_boo_001_displaylist_mesh[];
extern Gfx warp_pipe_boo_material_revert_render_settings[];

extern const GeoLayout warp_pipe_boo_green_locked_geo[];
extern Vtx warp_pipe_boo_green_locked_000_displaylist_mesh_vtx_0[64];
extern Gfx warp_pipe_boo_green_locked_000_displaylist_mesh_tri_0[];
extern Vtx warp_pipe_boo_green_locked_001_displaylist_mesh_vtx_0[4];
extern Gfx warp_pipe_boo_green_locked_001_displaylist_mesh_tri_0[];
extern Vtx warp_pipe_boo_green_locked_001_displaylist_mesh_vtx_1[16];
extern Gfx warp_pipe_boo_green_locked_001_displaylist_mesh_tri_1[];
extern Vtx warp_pipe_boo_green_locked_001_displaylist_mesh_vtx_2[38];
extern Gfx warp_pipe_boo_green_locked_001_displaylist_mesh_tri_2[];

extern Gfx warp_pipe_boo_green_locked_000_displaylist_mesh[];
extern Gfx warp_pipe_boo_green_locked_001_displaylist_mesh[];
extern Gfx warp_pipe_boo_green_locked_material_revert_render_settings[];

extern const GeoLayout warp_pipe_boo_green_unlocked_geo[];
extern Vtx warp_pipe_boo_green_unlocked_000_displaylist_mesh_vtx_0[64];
extern Gfx warp_pipe_boo_green_unlocked_000_displaylist_mesh_tri_0[];
extern Vtx warp_pipe_boo_green_unlocked_001_displaylist_mesh_vtx_0[4];
extern Gfx warp_pipe_boo_green_unlocked_001_displaylist_mesh_tri_0[];
extern Vtx warp_pipe_boo_green_unlocked_001_displaylist_mesh_vtx_1[16];
extern Gfx warp_pipe_boo_green_unlocked_001_displaylist_mesh_tri_1[];
extern Vtx warp_pipe_boo_green_unlocked_001_displaylist_mesh_vtx_2[38];
extern Gfx warp_pipe_boo_green_unlocked_001_displaylist_mesh_tri_2[];

extern Gfx warp_pipe_boo_green_unlocked_000_displaylist_mesh[];
extern Gfx warp_pipe_boo_green_unlocked_001_displaylist_mesh[];
extern Gfx warp_pipe_boo_green_unlocked_material_revert_render_settings[];

extern const GeoLayout warp_pipe_boo_red_geo[];
extern Vtx warp_pipe_boo_red_000_displaylist_mesh_vtx_0[64];
extern Gfx warp_pipe_boo_red_000_displaylist_mesh_tri_0[];
extern Vtx warp_pipe_boo_red_001_displaylist_mesh_vtx_0[4];
extern Gfx warp_pipe_boo_red_001_displaylist_mesh_tri_0[];
extern Vtx warp_pipe_boo_red_001_displaylist_mesh_vtx_1[16];
extern Gfx warp_pipe_boo_red_001_displaylist_mesh_tri_1[];

extern Gfx warp_pipe_boo_red_000_displaylist_mesh[];
extern Gfx warp_pipe_boo_red_001_displaylist_mesh[];
extern Gfx warp_pipe_boo_red_material_revert_render_settings[];

extern const GeoLayout warp_pipe_boo_yellow_locked_geo[];
extern Vtx warp_pipe_boo_yellow_locked_000_displaylist_mesh_vtx_0[64];
extern Gfx warp_pipe_boo_yellow_locked_000_displaylist_mesh_tri_0[];
extern Vtx warp_pipe_boo_yellow_locked_001_displaylist_mesh_vtx_0[4];
extern Gfx warp_pipe_boo_yellow_locked_001_displaylist_mesh_tri_0[];
extern Vtx warp_pipe_boo_yellow_locked_001_displaylist_mesh_vtx_1[16];
extern Gfx warp_pipe_boo_yellow_locked_001_displaylist_mesh_tri_1[];
extern Vtx warp_pipe_boo_yellow_locked_001_displaylist_mesh_vtx_2[38];
extern Gfx warp_pipe_boo_yellow_locked_001_displaylist_mesh_tri_2[];

extern Gfx warp_pipe_boo_yellow_locked_000_displaylist_mesh[];
extern Gfx warp_pipe_boo_yellow_locked_001_displaylist_mesh[];
extern Gfx warp_pipe_boo_yellow_locked_material_revert_render_settings[];

extern const GeoLayout warp_pipe_boo_yellow_unlocked_geo[];
extern Vtx warp_pipe_boo_yellow_unlocked_000_displaylist_mesh_vtx_0[64];
extern Gfx warp_pipe_boo_yellow_unlocked_000_displaylist_mesh_tri_0[];
extern Vtx warp_pipe_boo_yellow_unlocked_001_displaylist_mesh_vtx_0[4];
extern Gfx warp_pipe_boo_yellow_unlocked_001_displaylist_mesh_tri_0[];
extern Vtx warp_pipe_boo_yellow_unlocked_001_displaylist_mesh_vtx_1[16];
extern Gfx warp_pipe_boo_yellow_unlocked_001_displaylist_mesh_tri_1[];
extern Vtx warp_pipe_boo_yellow_unlocked_001_displaylist_mesh_vtx_2[38];
extern Gfx warp_pipe_boo_yellow_unlocked_001_displaylist_mesh_tri_2[];

extern Gfx warp_pipe_boo_yellow_unlocked_000_displaylist_mesh[];
extern Gfx warp_pipe_boo_yellow_unlocked_001_displaylist_mesh[];
extern Gfx warp_pipe_boo_yellow_unlocked_material_revert_render_settings[];

